name: Cypress Tests

on:
  pull_request:
    branches: ['master']

jobs:
  start-commenting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
      - name: start-commenting
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # package-lock.json && package.json file 동기화
      - name: Install
        run: rm -f package-lock.json && npm install

      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start
    needs: start-commenting
