name: Cypress Tests

on:
  pull_request:
    branches: ['master']
  issue_comment:
    types: [created]

jobs:
  start-commenting:
    if: github.event_name == 'pull_request' || contains(github.event.comment.body, 'run tests')
    runs-on: ubuntu-latest
    steps:
      - name: start-commenting
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            테스트 시작.. :mag_right:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-test:
    if: github.event_name == 'pull_request' || contains(github.event.comment.body, 'run tests')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # package-lock.json && package.json file 동기화
      - name: Install
        run: rm -f package-lock.json && npm install

      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start

      - if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            테스트 실패 :sob:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ success() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            테스트 통과 :+1:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    needs: start-commenting
