name: Cypress Tests

on:
  push:
    branches: [ "actions" ]

jobs:     
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # package.json file 변화 됐는데 package-lock.json은 업데이트 안됐을 때를 위해
      - name: Install 
        run: rm -f package-lock.json && npm install

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start
        
