name: Cypress Tests

on:
  push:
    branches: [ "actions" ]


jobs:     
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm start:test
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 200
          browser: chrome
          headless: true
          record: true
