name: pr_comment

on:
  issue_comment:
    types: [created]

jobs:
  pr-comment:
    if: contains(github.event.comment.body, 'run tests')
    uses: octo-org/example-repo/.github/workflows/cypress.yml.yml@master
